import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import ReactDropDown from './react-dropdown'

const inter = Inter({ subsets: ['latin'] })

interface DropdownOption {
    value: string,
    label: string
};

const DungeonsAndDragonsClasses: DropdownOption[] = [
    { value: '', label: 'Select a class' },
    { value: 'barbarian', label: 'Barbarian' },
    { value: 'bard', label: 'Bard' },
    { value: 'cleric', label: 'Cleric' },
    { value: 'druid', label: 'Druid' },
    { value: 'fighter', label: 'Fighter' },
    { value: 'monk', label: 'Monk' },
    { value: 'paladin', label: 'Paladin' },
    { value: 'ranger', label: 'Ranger' },
    { value: 'rogue', label: 'Rogue' },
    { value: 'sorcerer', label: 'Sorcerer' },
    { value: 'warlock', label: 'Warlock' },
    { value: 'wizard', label: 'Wizard' },
]

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <ReactDropDown options={DungeonsAndDragonsClasses} />
            </main>
        </>
    )
}
